// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cqk25K8CLoCEb3zRi62xhx
// Component: aANL8FUm5Gu7
import * as React from "react";
import {
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { useScreenVariants as useScreenVariantsirgN65KfHbzG } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: irgN65kfHbzG/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: cqk25K8CLoCEb3zRi62xhx/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: aANL8FUm5Gu7/css
import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: YBAm9F_DuZLz/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: SQqlqlFAdxvf/icon
import _12454851961582823590SvgIcon from "./icons/PlasmicIcon___12454851961582823590Svg"; // plasmic-import: 7Cgb7QZmd5IS/icon
import _13616027201551939471SvgIcon from "./icons/PlasmicIcon___13616027201551939471Svg"; // plasmic-import: XqnN_E010kh-/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: ILKk6KPFb1sy/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: -A6eT55LtL6T/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: xp2DxXUu0tz6/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: GvR_m76KYdCJ/icon

createPlasmicElementProxy;

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

const $$ = {};

function PlasmicFooter__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsirgN65KfHbzG()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__tqOze)}>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__oSKwa)}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__rlg5Z)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__qY82)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__diCfp
                )}
              >
                {"Contact us"}
              </h4>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__raW2Q)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jfx0R)}>
                  <_14655891761535698998SvgIcon
                    className={classNames(projectcss.all, sty.svg___0FyQ)}
                    role={"img"}
                  />
                </div>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vB8R6)}
                  >
                    <Icon8Icon
                      className={classNames(projectcss.all, sty.svg__hQf14)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zRdSx)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rjQfT
                    )}
                  >
                    {"Location address  121 "}
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6C1Bf)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vwtCv)}>
                  <_12454851961582823590SvgIcon
                    className={classNames(projectcss.all, sty.svg__jUzfL)}
                    role={"img"}
                  />
                </div>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ucm5C)}
                  >
                    <Icon8Icon
                      className={classNames(projectcss.all, sty.svg__c5PUa)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___1707)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b379
                    )}
                  >
                    {"098436454353"}
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9FOp4)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__p8Eoi)}>
                  <_13616027201551939471SvgIcon
                    className={classNames(projectcss.all, sty.svg__tCmKb)}
                    role={"img"}
                  />
                </div>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1DmF8)}
                  >
                    <Icon8Icon
                      className={classNames(projectcss.all, sty.svg__aMYrd)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ywylk)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r7ND6
                    )}
                  >
                    {"info@gmail.com"}
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__am2Hl)}
              >
                <Icon3Icon
                  className={classNames(projectcss.all, sty.svg__xj3SV)}
                  role={"img"}
                />

                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__bcOa0)}
                  role={"img"}
                />

                <Icon28Icon
                  className={classNames(projectcss.all, sty.svg__uJwyn)}
                  role={"img"}
                />
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__mBvLh)}
          >
            <h4
              className={classNames(
                projectcss.all,
                projectcss.h4,
                projectcss.__wab_text,
                sty.h4__eTmXi
              )}
            >
              {"Categories"}
            </h4>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link___7PVxs
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg___21Nr)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nzq9U
                )}
              >
                {"Apartments(12)"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__foMbf)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__dfpwU
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg___8FDet)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4Ksw7
                )}
              >
                {"Condos(8)"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__oyy0I)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__eD1GO
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__nIuXr)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nicsi
                )}
              >
                {"Industrial(1)"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__bSlJu)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__sotxI
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__rmZ0Q)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eyqxI
                )}
              >
                {"Retail(4)"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__dJn8D)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__ghgAd)}
          >
            <h4
              className={classNames(
                projectcss.all,
                projectcss.h4,
                projectcss.__wab_text,
                sty.h4__x5EFf
              )}
            >
              {"Company"}
            </h4>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__srEnF
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__isqMn)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hdWu3
                )}
              >
                {"About"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg___8W26J)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__xy7Zh
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__o04X)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tVQt
                )}
              >
                {"Contact us"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__b17Sf)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link___2GxBw
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__zgODn)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rguSs
                )}
              >
                {"Careers"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__t6Oct)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__qmvlz
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__taPxT)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hHc3M
                )}
              >
                {"Media"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__egAoP)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__swvWd)}
          >
            <h4
              className={classNames(
                projectcss.all,
                projectcss.h4,
                projectcss.__wab_text,
                sty.h4__m61Nv
              )}
            >
              {"Navigation"}
            </h4>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__yQZnC
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__tm3Mo)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7Qg5Y
                )}
              >
                {"Nav link"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__mzu33)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__mcFv4
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__ifUz)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bBssg
                )}
              >
                {"Nav link"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__riLo)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__iGbwj
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__uxdwm)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9AvU
                )}
              >
                {"Nav link"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__x9ANf)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
            <Stack__
              as={PlasmicLink__}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__h6U3R
              )}
              platform={"react"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__rUoEs)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dUG8
                )}
              >
                {"Nav link"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg___2RIaf)}
                  role={"img"}
                />
              ) : null}
            </Stack__>
          </Stack__>
        </Stack__>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__cSdFy)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___1KvBh
          )}
        >
          <React.Fragment>
            <React.Fragment>
              {
                "\u00a9 Company. All rights reserved. This site proudly built with "
              }
            </React.Fragment>
            {
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  projectcss.plasmic_default__inline,
                  sty.link__z0Eg3
                )}
                href={"https://www.plasmic.app"}
                platform={"react"}
              >
                {"Plasmic"}
              </PlasmicLink__>
            }

            <React.Fragment>{"."}</React.Fragment>
          </React.Fragment>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
