// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cqk25K8CLoCEb3zRi62xhx
// Component: YZ6d24xk9Ehw
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Header from "../../Header"; // plasmic-import: WXD7ODgB7HmJ/component
import ListingListBox from "../../ListingListBox"; // plasmic-import: 71q-FmEDiu-m/component
import ContactSectionFooterTop from "../../ContactSectionFooterTop"; // plasmic-import: DoZzMN57XJOO/component
import Footer from "../../Footer"; // plasmic-import: aANL8FUm5Gu7/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: cqk25K8CLoCEb3zRi62xhx/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: YZ6d24xk9Ehw/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: GvR_m76KYdCJ/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: EfgAiJwKIYqj/icon
import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: YBAm9F_DuZLz/icon
import kitchen16871211280JpgGRNdPxQtiW from "./images/kitchen16871211280Jpg.jpg"; // plasmic-import: g_R_NdPxQtiW/picture
import house24833361280JpgVbNfQZwMWsy4 from "./images/house24833361280Jpg.jpg"; // plasmic-import: VBNfQZwMWsy4/picture
import house59026651280JpgDz3Av8FoccF5 from "./images/house59026651280Jpg.jpg"; // plasmic-import: dz3av8foccF5/picture
import staging28164641280JpgRhNj8G3AqUr4 from "./images/staging28164641280Jpg.jpg"; // plasmic-import: rhNj8g3AQUr4/picture
import realEstate32976251280JpgGr3IcWPpxGf from "./images/realEstate32976251280Jpg.jpg"; // plasmic-import: GR3icW_PPXGf/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__p9L)}>
            <div className={classNames(projectcss.all, sty.freeBox__xoO6H)}>
              <div className={classNames(projectcss.all, sty.freeBox__hd1KY)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___3ZaKd)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"The Keys to Your Dream House"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6MSbT
                    )}
                  >
                    {
                      '"Discover Your Dream Home for Rent Today!\nFind the Perfect Space to \nCall Your Own with Our Wide Selection of Rental Properties.!"'
                    }
                  </div>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__qTMuj
                    )}
                    href={`/contact-us`}
                    platform={"react"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___1KCOw)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7CTmv
                      )}
                    >
                      {"Explore Now"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___4PQf4)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kdjyW)}>
                <div className={classNames(projectcss.all, sty.freeBox__k41Wn)}>
                  <ChevronDownIcon
                    className={classNames(projectcss.all, sty.svg__qxiO)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__jyzk8)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__u1Soe)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__gohRv
                  )}
                >
                  {"Find your next dream home."}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mfAx3
                  )}
                >
                  {"A euismod eros a hendrerit tristique suscipit sit ."}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column___5OeHz)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__oWwrz
                    )}
                    slot={
                      <React.Fragment>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__qbyp5
                          )}
                        >
                          {"A Grand Modern Home"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gpGmQ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___6ZwpQ
                            )}
                          >
                            <_14655891761535698998SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__s0Lme
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nw24A
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ru9EG
                              )}
                            >
                              {"Location address  121 sqaure"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__d2ND8
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tigeC
                            )}
                          >
                            {"from $ 24,00"}
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__nZpQo)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__qDhXv
                    )}
                    slot={
                      <React.Fragment>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__zjCy
                          )}
                        >
                          {"Home real state"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__b9R9F
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___6Y7Z5
                            )}
                          >
                            <_14655891761535698998SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__aaidJ
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___9E4Sn
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dt49G
                              )}
                            >
                              {"Location address  121 sqaure"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___35GYt
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jkXoz
                            )}
                          >
                            {"from $ 34,00"}
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1HAzK)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: kitchen16871211280JpgGRNdPxQtiW,
                        fullWidth: 1280,
                        fullHeight: 663,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__bkEtu)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__lqvNb
                    )}
                    slot={
                      <React.Fragment>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__hYqg
                          )}
                        >
                          {"A Grand Modern Home"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xlRPl
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___0GwNg
                            )}
                          >
                            <_14655891761535698998SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ggn4M
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___6G7Le
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wHjJ
                              )}
                            >
                              {"Location address  121 sqaure"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mqykk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__y5Wtk
                            )}
                          >
                            {"from $ 24,00"}
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__kWNX)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: house24833361280JpgVbNfQZwMWsy4,
                        fullWidth: 1280,
                        fullHeight: 895,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__v5J8X)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__osjN
                    )}
                    slot={
                      <React.Fragment>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__t8Q2H
                          )}
                        >
                          {"A Grand Modern Home"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wtp0F
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___55WNv
                            )}
                          >
                            <_14655891761535698998SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__tNNlH
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__cUvIf
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nDnyH
                              )}
                            >
                              {"Location address  121 sqaure"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sKHs1
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__j3Jn
                            )}
                          >
                            {"from $ 24,00"}
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zbZvJ)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: house59026651280JpgDz3Av8FoccF5,
                        fullWidth: 1280,
                        fullHeight: 851,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__neAbi)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__qX8Ag
                    )}
                    slot={
                      <React.Fragment>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__rf1Ak
                          )}
                        >
                          {"A Grand Modern Home"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ls8Lf
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aZ4Fy
                            )}
                          >
                            <_14655891761535698998SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___1PZpx
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uatBy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dBzA
                              )}
                            >
                              {"Location address  121 sqaure"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9RaNe
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ua7Ux
                            )}
                          >
                            {"from $ 24,00"}
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ohzoN)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: staging28164641280JpgRhNj8G3AqUr4,
                        fullWidth: 1280,
                        fullHeight: 853,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__sihn8)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__i9Fw
                    )}
                    slot={
                      <React.Fragment>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__d0R9L
                          )}
                        >
                          {"A Grand Modern Home"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ozYt3
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__waRjg
                            )}
                          >
                            <_14655891761535698998SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__g4Vw8
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__e7Rrj
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bZOu
                              )}
                            >
                              {"Location address  121 sqaure"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cynEh
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gN5XO
                            )}
                          >
                            {"from $ 24,00"}
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yHavr)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: realEstate32976251280JpgGr3IcWPpxGf,
                        fullWidth: 1280,
                        fullHeight: 853,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__zRcag)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__t5Nn)}>
              <div className={classNames(projectcss.all, sty.freeBox__nlste)}>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"left2"}
                  data-plasmic-override={overrides.left2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.left2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i2MiE
                    )}
                  >
                    {"Find us"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__elU0D
                    )}
                  >
                    {"Join us at our next house tour."}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l547X
                    )}
                  >
                    {
                      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
                    }
                  </div>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ioYLo
                    )}
                    href={`/contact-us`}
                    platform={"react"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__pdF0L)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oji5
                      )}
                    >
                      {"Connect"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__v3JRq)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <ContactSectionFooterTop
            data-plasmic-name={"contactSectionFooterTop"}
            data-plasmic-override={overrides.contactSectionFooterTop}
            className={classNames(
              "__wab_instance",
              sty.contactSectionFooterTop
            )}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </Stack__>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "h1",
    "foreground2",
    "columns",
    "left2",
    "contactSectionFooterTop",
    "footer"
  ],

  header: ["header"],
  h1: ["h1"],
  foreground2: ["foreground2"],
  columns: ["columns"],
  left2: ["left2"],
  contactSectionFooterTop: ["contactSectionFooterTop"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    h1: makeNodeComponent("h1"),
    foreground2: makeNodeComponent("foreground2"),
    columns: makeNodeComponent("columns"),
    left2: makeNodeComponent("left2"),
    contactSectionFooterTop: makeNodeComponent("contactSectionFooterTop"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
